# -*- coding: utf-8 -*-
"""실습용.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ot6eh0ohsdR-99rSrlNnG-eNpBKHeVro
"""

print ("테스트")





